/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  tutorialSidebar: [
    'index',
    {
      type: 'category',
      label: 'Regolamenti',
      items: ['Regolamenti/regolamento', 'Regolamenti/regolamento-lands'],
    },
    {
      type: 'category',
      label: 'Mob Custom',
      items: ['bloodmoon',
        {
          type: 'category',
          label: 'Boss',
          items: ['boss/index', 'boss/tier-1'],
        }],
    },
    {
      type: 'category',
      label: 'Items Custom',
      items: [{
        type: 'category',
        label: 'Enderite',
        items: ['enderite/index', 'enderite/armatura', 'enderite/utensili'],
      }, {
        type: 'category',
        label: 'Spade dell\'Anima',
        items: ['spade-mob/index', 'spade-mob/creepersword', 'spade-mob/skeletonsword', 'spade-mob/spidersword', 'spade-mob/zombiesword'],
      }],
    },
    {
      type: 'category',
      label: 'Lista Shops',
      items: ['shops/index', 'shops/agricoltore', 'shops/alchimista', 'shops/architette', 'shops/boscaiolo', 'shops/cacciatore', 'shops/chierco', 'shops/minatore', 'shops/pescatore', 'shops/sarta'],
    }
  ]


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
